name: Build/Test

on: [ push, pull_request ]

jobs:
  build:
    name: build/test on node versions

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 19.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # 2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # 3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn type-check
      - run: yarn lint
      - run: yarn build-prod
      - run: yarn set-plugin-version 0.0.0
