name: Test-Release

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: test release

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # 2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443

      - name: Get branch name
        uses: tj-actions/branch-names@a594c1e96eab7790611fdaf5bc8f76ea55cedabd # 6.3
        id: branch-name

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # 3.2
        id: semantic
        with:
          dry_run: true
          semantic_version: 19.0.2
          branch: ${{ steps.branch-name.outputs.current_branch }}
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/exec@6.0.3
            @amille/semantic-release-plugins@3.3.12
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release version: ${{ steps.semantic.outputs.new_release_version }}
